version: "3.5"

services:
  api-poc:
    container_name: api-poc
    build:
      context: ./api-poc
      dockerfile: Dockerfile
    volumes:
      - ./api-poc:/var/www/html
    ports:
      - "1214:1214"
    depends_on:
      - api-poc-tipo-cambio
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 256M


  api-poc-tipo-cambio:
    container_name: api-poc-tipo-cambio
    build:
      context: ./api-poc-tipo-cambio
      dockerfile: Dockerfile
    volumes:
      - ./api-poc-tipo-cambio:/var/www/html
    ports:
      - "1215:1215"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 256M

